### ISSUE TITLE
Questions for the paper

### ISSUE THREAD

**Issue by mrgreen3325** [felixcheng97/IICNet#1]
Thanks for your work.
May I know that is the e_(ref) in the paper equal to the exact middle input images, e.g. f1, f2, f3, f4, f5, then f3?
e_(ref) no need to embed the f3 right?
Thanks.

**Comment by felixcheng97** [comment]
Thanks for your question. 

For your first question, I think you are refering to the Spatial-Temporal Video Embedding task. Partially correct, because in our setting, e_(ref) can be equal to the middle input image (f3) or the downsampled the middle input image (f3_down).

For your second question, e_(ref) is the guiding ground truth for the embedding image e. We hope e and e_(ref) look similar, but in reality they cannot be exactly the same. Furthermore, e_(ref) can also be f3_down, which means that e_(ref) can be the downsampled version of f3. So, we still need to embed f3 into the embedding image e.

Hope these help.

**Comment by mrgreen3325** [comment]
Thanks for the reply.
I notice that the davis_num05_step05_train.json is not consecutive frames, e.g. jump by 5 frames.
It seems that the content of a batch of that frames will have big changes, right?
Thanks.

**Comment by felixcheng97** [comment]
Thanks for the question.

Yes, we use non-consecutive frames (step = 5) for training, because we hope the network can deal with and embed larger motions. In Table 1, we report testing results with step = 1, 3, 5; in Table 2 and Table 6 (the video embedding column), the results are tested with step = 1.

Hope these help.

**Comment by mrgreen3325** [comment]
Thanks a lot.
May I also know in the real situation, e.g. a sender has a video f1, f2,..., f20, with using range 5.
The iccnet will embed f1,...,f5 to fe_1, f6,...,f10 to fe_2, f11,...,f15 to fe_3, f16,...,f20 to fe_4.
fe_1 - fe_4 will be sent to the receiver and converted back to f1 - f20 by the reverse operation of iccnet.
Is that the operation conduct in the real situation?
Thanks.

**Comment by felixcheng97** [comment]
Thanks for your question. Yes, this is the operation to be conducted in real cases.

**Comment by felixcheng97** [comment]
I am closing this issue since the last question was asked more than 2 weeks ago. Feel free to reopen this issue if you have any further questions. Thanks.
