### ISSUE TITLE
No .json file

### ISSUE THREAD

**Issue by TomTomTommi** [felixcheng97/IICNet#2]
Hi, when I ran the codes, I failed to find the .json file and get the bug:

"FileNotFoundError: [Errno 2] No such file or directory: '../annotation/flicker1024_test.json'"

**Comment by felixcheng97** [comment]
Thanks for your message. Here are my replies:

1. Have you download the files and generate the annotation json files according to "Task 2: Mononizing Binocular Images" under "Dataset Preparation"?
2. "../annotation/flicker1024_test.json" is a relative path (by default it is relative to the directory of the test.py script). If you are running your own testing scripts in other directories, make sure that "../annotation/flicker1024_test.json" is a valid relative path to the directory of your own testing scripts.
3. Have you followed the instructions stated in README to run the testing scripts? (e.g. you should cd into the "./codes" directory to run test.py, since we are using the relative path in our scripts")

Hope these helps.

**Comment by TomTomTommi** [comment]
Thanks for your reply! 
Following "Dataset Preparation" in "Task 2: Mononizing Binocular Images", there have four train folders: Train_1, Train_2, Train_3, Train_4. But in the link of Flickr1024, when I download, I can only find one train folder: Train. 
Could you please tell me how to split Train into these four folders? Thanks for your time.

**Comment by felixcheng97** [comment]
Sorry for the late reply. Here are my replies:

I just noticed that the datasets are zipped differently in the two versions in Baidu Drive and Google Drive from the official link ([https://yingqianwang.github.io/Flickr1024/](https://yingqianwang.github.io/Flickr1024/)). The splits should be correct if you download the ones from the the Google Drive link. If you download the dataset from the Baidu Drive link, the splits are easy: basically files with train sample id 001-200, 201-400, 401-600, 601-800 are stored in Train_1, Train_2, Train_3, Train_4, repectively.

Hope these helps.

**Comment by TomTomTommi** [comment]
Thanks for your time!

**Comment by felixcheng97** [comment]
I am closing this issue since the problem has been resolved.
